apiVersion: v2
name: search
description: A Helm chart for Helx Search components. This chart installs Dug, TranQL , Airflow and Redis.

# A chart can be either an 'application' or a 'library' chart.
#
# Application charts are a collection of templates that can be packaged into versioned archives
# to be deployed.
#
# Library charts provide useful utilities or functions for the chart developer. They're included as
# a dependency of application charts to inject those utilities and functions into the rendering
# pipeline. Library charts do not define any templates and therefore cannot be deployed.
type: application

# This is the chart version. This version number should be incremented each time you make changes
# to the chart and its templates, including the app version.
# Versions are expected to follow Semantic Versioning (https://semver.org/)
version: 5.1.0


appVersion: "2.10.2"

dependencies:
  - name: airflow
    version: "8.8.0"
    condition: airflow.enabled
    repository: "https://airflow-helm.github.io/charts"
  - name: elasticsearch
    version: "8.5.1"
    repository: "https://helm.elastic.co"
    condition: elasticsearch.enabled
  - name: redis
    version: "18.1.1"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
  - name: tranql
    version: "0.4.2"
    condition: tranql.enabled
    repository: "@helx-charts"
  - name: redis-insight
    version: "0.1.0"
    condition: redis-insight.enabled
    repository: "@helx-charts"
  - name: ui
    condition: ui.enabled
    version: "^1.3.0"
    repository: "@helx-charts"
